// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg-48S3uPd2RZlXuV5k9_VPozgy7laH4c',
    appId: '1:582871296985:web:92e16d7d756330595087c8',
    messagingSenderId: '582871296985',
    projectId: 'demoflutter-1a6a9',
    authDomain: 'demoflutter-1a6a9.firebaseapp.com',
    storageBucket: 'demoflutter-1a6a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo4ASf0pUfS5N3SfZxhhggqUUWn_EfyiU',
    appId: '1:582871296985:android:1aa08dc7800c52695087c8',
    messagingSenderId: '582871296985',
    projectId: 'demoflutter-1a6a9',
    storageBucket: 'demoflutter-1a6a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL3ljtimauqOJRQFSP5PlbLedBu4CA-0w',
    appId: '1:582871296985:ios:896a00858588d9a05087c8',
    messagingSenderId: '582871296985',
    projectId: 'demoflutter-1a6a9',
    storageBucket: 'demoflutter-1a6a9.appspot.com',
    iosBundleId: 'com.example.demoFlu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL3ljtimauqOJRQFSP5PlbLedBu4CA-0w',
    appId: '1:582871296985:ios:934ec882f88b362d5087c8',
    messagingSenderId: '582871296985',
    projectId: 'demoflutter-1a6a9',
    storageBucket: 'demoflutter-1a6a9.appspot.com',
    iosBundleId: 'com.example.demoFlu.RunnerTests',
  );
}
